.TH "include Directory Reference" 3 "Wed Dec 9 2020" "HyperProtocol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBhyper\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBhyper\&.h\fP"
.br
.RI "Common functions and variables\&. "
.in -1c
