.TH "include/hyper/hyper_network.h" 3 "Wed Dec 9 2020" "HyperProtocol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/hyper/hyper_network.h
.SH SYNOPSIS
.br
.PP
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <hyper\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCONNECTION_CLOSED\fP   0"
.br
.ti -1c
.RI "#define \fBINVALID_SOCKET\fP   \-1"
.br
.ti -1c
.RI "#define \fBSOCKET_ERROR\fP   \-1"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fBSOCKET\fP"
.br
.ti -1c
.RI "typedef struct sockaddr_in \fBSOCKADDR_IN\fP"
.br
.ti -1c
.RI "typedef struct sockaddr \fBSOCKADDR\fP"
.br
.ti -1c
.RI "typedef socklen_t \fBSOCKLEN\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBHYPERSTATUS\fP \fBHyperNetworkInit\fP (void)"
.br
.ti -1c
.RI "\fBHYPERSTATUS\fP \fBHyperCloseSocket\fP (\fBSOCKET\fP sock)"
.br
.ti -1c
.RI "\fBHYPERSTATUS\fP \fBHyperSocketCleanup\fP (void)"
.br
.ti -1c
.RI "\fBHYPERSTATUS\fP \fBHyperSocket\fP (\fBSOCKET\fP *sock)"
.br
.ti -1c
.RI "\fBHYPERSTATUS\fP \fBHyperConnectServer\fP (\fBSOCKET\fP *sock, const char *cpServerIP, const unsigned short usPort)"
.br
.ti -1c
.RI "\fBHYPERSTATUS\fP \fBHyperStartServer\fP (\fBSOCKET\fP *sock, const unsigned short usPort)"
.br
.ti -1c
.RI "\fBHYPERSTATUS\fP \fBHyperServerListen\fP (const \fBSOCKET\fP sockServer, \fBSOCKET\fP *sockClient)"
.br
.ti -1c
.RI "\fBHYPERSTATUS\fP \fBHyperReceiveCommand\fP (const \fBSOCKET\fP sock, char *cpCommand, size_t stMaxCommandLength)"
.br
.ti -1c
.RI "\fBHYPERSTATUS\fP \fBHyperSendCommand\fP (const \fBSOCKET\fP sock, const char *cpCommand)"
.br
.ti -1c
.RI "\fBHYPERSTATUS\fP \fBHyperSendStatus\fP (const \fBSOCKET\fP sock, const unsigned short status)"
.br
.ti -1c
.RI "\fBHYPERSTATUS\fP \fBHyperReceiveStatus\fP (const \fBSOCKET\fP sock, unsigned short *status)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CONNECTION_CLOSED   0"

.PP
Definition at line 4 of file hyper_network\&.h\&.
.SS "#define INVALID_SOCKET   \-1"

.PP
Definition at line 25 of file hyper_network\&.h\&.
.SS "#define SOCKET_ERROR   \-1"

.PP
Definition at line 26 of file hyper_network\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct sockaddr \fBSOCKADDR\fP"

.PP
Definition at line 22 of file hyper_network\&.h\&.
.SS "typedef struct sockaddr_in \fBSOCKADDR_IN\fP"

.PP
Definition at line 21 of file hyper_network\&.h\&.
.SS "typedef int \fBSOCKET\fP"

.PP
Definition at line 19 of file hyper_network\&.h\&.
.SS "typedef socklen_t \fBSOCKLEN\fP"

.PP
Definition at line 23 of file hyper_network\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBHYPERSTATUS\fP HyperCloseSocket (\fBSOCKET\fP sock)"

.SS "\fBHYPERSTATUS\fP HyperConnectServer (\fBSOCKET\fP * sock, const char * cpServerIP, const unsigned short usPort)"

.SS "\fBHYPERSTATUS\fP HyperNetworkInit (void)"

.SS "\fBHYPERSTATUS\fP HyperReceiveCommand (const \fBSOCKET\fP sock, char * cpCommand, size_t stMaxCommandLength)"

.SS "\fBHYPERSTATUS\fP HyperReceiveStatus (const \fBSOCKET\fP sock, unsigned short * status)"

.SS "\fBHYPERSTATUS\fP HyperSendCommand (const \fBSOCKET\fP sock, const char * cpCommand)"

.SS "\fBHYPERSTATUS\fP HyperSendStatus (const \fBSOCKET\fP sock, const unsigned short status)"

.SS "\fBHYPERSTATUS\fP HyperServerListen (const \fBSOCKET\fP sockServer, \fBSOCKET\fP * sockClient)"

.SS "\fBHYPERSTATUS\fP HyperSocket (\fBSOCKET\fP * sock)"

.SS "\fBHYPERSTATUS\fP HyperSocketCleanup (void)"

.SS "\fBHYPERSTATUS\fP HyperStartServer (\fBSOCKET\fP * sock, const unsigned short usPort)"

.SH "Author"
.PP 
Generated automatically by Doxygen for HyperProtocol from the source code\&.
