.TH "src/hyper.c" 3 "Wed Dec 9 2020" "HyperProtocol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/hyper.c
.SH SYNOPSIS
.br
.PP
\fC#include 'hyper\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBHYPERSTATUS\fP \fBHyperMemAlloc\fP (void **src, size_t size)"
.br
.ti -1c
.RI "\fBHYPERSTATUS\fP \fBHyperMemFree\fP (void *src)"
.br
.ti -1c
.RI "\fBHYPERSTATUS\fP \fBHyperMemRealloc\fP (void **src, size_t size)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBHYPERSTATUS\fP HyperMemAlloc (void ** src, size_t size)"

.SS "\fBHYPERSTATUS\fP HyperMemFree (void * src)"

.SS "\fBHYPERSTATUS\fP HyperMemRealloc (void ** src, size_t size)"

.SH "Author"
.PP 
Generated automatically by Doxygen for HyperProtocol from the source code\&.
