.TH "src/hyper_file.c" 3 "Wed Dec 9 2020" "HyperProtocol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/hyper_file.c
.SH SYNOPSIS
.br
.PP
\fC#include <hyper/hyper_file\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBHYPERSTATUS\fP \fBHyperReadFileC\fP (FILE *in, void **dataptr, size_t *sizeptr)"
.br
.ti -1c
.RI "\fBHYPERSTATUS\fP \fBHyperReceiveFile\fP (const \fBSOCKET\fP sockServer, void **lpBuffer, unsigned long *ulSize)"
.br
.ti -1c
.RI "\fBHYPERSTATUS\fP \fBHyperReadFile\fP (const char *cpFilePath, \fBHYPERFILE\fP *lpBuffer, size_t *lpFileSize)"
.br
.ti -1c
.RI "\fBHYPERSTATUS\fP \fBHyperWriteFileC\fP (FILE *pFile, const \fBHYPERFILE\fP hfBuffer, const size_t stFileSize)"
.br
.ti -1c
.RI "\fBHYPERSTATUS\fP \fBHyperWriteFile\fP (const char *cpFilePath, const \fBHYPERFILE\fP hfBuffer, const size_t stFileSize)"
.br
.ti -1c
.RI "\fBHYPERSTATUS\fP \fBHyperSendFile\fP (const \fBSOCKET\fP sockServer, \fBHYPERFILE\fP *lpBuffer, const unsigned long ulSize)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBHYPERSTATUS\fP HyperReadFile (const char * cpFilePath, \fBHYPERFILE\fP * lpBuffer, size_t * lpFileSize)"

.SS "\fBHYPERSTATUS\fP HyperReadFileC (FILE * in, void ** dataptr, size_t * sizeptr)"

.SS "\fBHYPERSTATUS\fP HyperReceiveFile (const \fBSOCKET\fP sockServer, void ** lpBuffer, unsigned long * ulSize)"

.SS "\fBHYPERSTATUS\fP HyperSendFile (const \fBSOCKET\fP sockServer, \fBHYPERFILE\fP * lpBuffer, const unsigned long ulSize)"

.SS "\fBHYPERSTATUS\fP HyperWriteFile (const char * cpFilePath, const \fBHYPERFILE\fP hfBuffer, const size_t stFileSize)"

.SS "\fBHYPERSTATUS\fP HyperWriteFileC (FILE * pFile, const \fBHYPERFILE\fP hfBuffer, const size_t stFileSize)"

.SH "Author"
.PP 
Generated automatically by Doxygen for HyperProtocol from the source code\&.
